trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_EC2_METADATA_DISABLED: 'true'
  AWS_DEFAULT_REGION: 'us-east-2'

steps:
- script: echo "Hello, world!"
  displayName: 'Run a one-line script'

- script: |
    echo "Add other tasks to build, test, and deploy your project."
    echo "See https://aka.ms/yaml"
  displayName: 'Run a multi-line script'

- script: |
    sudo apt-get update
    sudo apt-get install -y awscli
  displayName: 'Install AWS CLI'

- script: |
    aws --version
  displayName: 'Check AWS CLI version'

- script: |
    aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
    aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
    #aws configure set aws_session_token $(AWS_SESSION_TOKEN)
  displayName: 'Configure AWS CLI'

- script: |
    aws s3 ls
  displayName: 'AWS CLI precheck'

- script: |
    aws ec2 describe-instances --query 'Reservations[*].Instances[*].InstanceId' --output text --debug > instance_ids.txt
  displayName: 'List EC2 instances'

- script: |
    for instance_id in $(cat instance_ids.txt); do
      os_type=$(aws ec2 describe-instances --instance-id $instance_id --query 'Reservations[*].Instances[*].Platform' --output text)
      if [[ "$os_type" == "windows" ]]; then
        echo "Windows OS detected for instance $instance_id. Cloning repository and executing HOTS-Windows-v3-withAWSCLI.ps1"
        aws ssm send-command \
          --instance-ids $instance_id \
          --document-name "AWS-RunPowerShellScript" \
          --comment "Cloning repository and running PowerShell script" \
          --parameters commands=["git clone https://github.com/geeklert/automation.git C:\\Temp\\", "powershell -File C:\\Temp\\scripts\\HOTS-Windows-v3-withAWSCLI.ps1"]
      else
        echo "Linux OS detected for instance $instance_id. Cloning repository and executing HOTS-linux-v3-with-AWSCLI.sh"
        aws ssm send-command \
          --instance-ids $instance_id \
          --document-name "AWS-RunShellScript" \
          --comment "Cloning repository and running Shell script" \
          --parameters commands=["git clone https://github.com/geeklert/automation.git /tmp/", "bash /tmp/scripts/HOTS-linux-v4-with-exceloutput.sh"]
      fi
    done
  displayName: 'Clone repository and execute scripts on EC2 instances based on OS type'
