trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_EC2_METADATA_DISABLED: 'true'
  AWS_DEFAULT_REGION: 'us-east-2'

steps:
- script: echo "Hello, world!"
  displayName: 'Run a one-line script'

- script: |
    echo "Add other tasks to build, test, and deploy your project."
    echo "See https://aka.ms/yaml"
  displayName: 'Run a multi-line script'

- script: |
    sudo apt-get update
    sudo apt-get install -y awscli
  displayName: 'Install AWS CLI'

- script: |
    aws --version
  displayName: 'Check AWS CLI version'

- script: |
    aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
    aws configure set aws_secret_access_key $(aws_secret_access_key)
    aws configure set aws_session_token $(aws_session_token)
  displayName: 'Configure AWS CLI'

- script: |
    aws s3 ls
  displayName: 'AWS CLI precheck'

- script: |
    aws ec2 describe-instances --query 'Reservations[*].Instances[*].InstanceId' --output text --debug > instance_ids.txt
  displayName: 'List EC2 instances'

- script: |
    for instance_id in $(cat instance_ids.txt); do
      aws ssm send-command \
        --instance-ids $instance_id \
        --document-name "AWS-RunShellScript" \
        --comment "Running Python script" \
        --parameters 'commands=["sudo yum update -y && sudo yum install -y git python3 && mkdir -p /tmp/automation && git clone https://github.com/geeklert/automation.git /tmp/automation && mv /tmp/automation/scripts/HOTS-linux-v3-with-AWSCLI.sh /tmp/automation/HOTS-linux-v3-with-AWSCLI.sh && sudo chmod +x /tmp/automation/HOTS-linux-v3-with-AWSCLI.sh && echo Current directory: $(pwd) && echo Listing files: && ls -la && sudo bash -x /tmp/automation/HOTS-linux-v3-with-AWSCLI.sh"]'
    done
  displayName: 'Execute Python script on EC2 instances'